= Admin Console v2 local tweaks

NOTE: Admin Console v2 is in Alpha version and requires some tweaks in your local dev environment to function properly.

== Load admin route

In order to load the /admin route to access the admin console V2, please follow these instructions:

Edit the file *springboard-open-ent/ent-core.embedded.json*, as described below:

1. In the *external-modules* section, add:

....
    {
      "name": "org.entcore~admin~<version>",
      "config": {
        "main":"org.entcore.admin.Admin",
        "port": 8089,
        "mode": "dev",
        "auto-redeploy": false,
        "host" : "http://localhost:8089",
        "app-name" : "Admin",
        "app-address" : "http://localhost:8089/admin",
        "app-icon" : "admin-large"
      }
    }
....

where <version> has to be replaced by entcore version number

2. In the *http-proxy* section, add:

....
    {
      "location": "/admin",
      "proxy_pass": "http://localhost:8089"
    }
....

== Webpack dev server

Webpack dev server loads javascript in memory and automatically refreshes the browser after code changes in your editor.

Admin console V2 through Webpack dev server is reachable on port 9000. 

Webpack dev server proxies request to vertx. A tweak is needed for proxy to work fine. Please follow these instructions to apply the tweak:

Edit the file *springboard-open-ent/ent-core.embedded.json*, as described below:

1. In the *http-proxy* section, change the version of http-proxy to 1.2-SNAPSHOT:

....
    "name": "fr.wseduc~http-proxy~1.2-SNAPSHOT",
.... 

With Webpack dev server, you will access your app on port 9000, we need to configure this new URL for the theme picker, as follow:

Edit *test.properties*:

1. Add leo theme for localhost:9000 in skins property:

....
    skins={"localhost:8090":"leo", "localhost:9000": "leo"}
....
