= Admin v2 - Build Process
David Caudeli <david.caudeli@opendigitaleducation.com>
v1.0, 2017-08-09
:toc:

This document describes the admin console v2 build process for developers

== Requirements

=== Dev tools

* git
* npm
* gulp (3.9.1)
* gradle (1.6)

=== Clone admin console v2 project

....
$ git clone git@github.com:entcore/entcore.git
$ cd entcore
$ git checkout admin-v2
....

=== Install npm dependencies

....
$ npm install
....

=== Springboard configuration

In your springboard gradle.properties file, set entcore version to 2.0-SNAPSHOT and springboard plugin version to 1.0-SNAPSHOT:

....
entCoreVersion=2.0-SNAPSHOT
springboardPluginVersion=1.0-SNAPSHOT
....

In test.properties/conf.properties, set entcore version to 2.0-SNAPSHOT and add "localhost:9000" to skins array:

....
entcoreVersion=2.0-SNAPSHOT
skins={"localhost:8090":"leo", "localhost:9000": "leo"}
....

== Dev build

Check "0. Requirements" before

=== Build front

....
$ gulp adminV2-clean
$ gulp adminV2-build-dev
....

=== Build admin module

....
$ gradle :admin:clean
$ gradle :admin:install
....

=== Deploy admin module to local springboard

....
$ cd ${springboard_dir}
$ rm -rf mods/org.entcore~admin~2.0-SNAPSHOT/
$ vertx runMod org.entcore~infra~2.0-SNAPSHOT -conf ent-core.embedded.json
....

Test app in browser => http://localhost:8090/admin

== Dev "Hot Reload" build

IMPORTANT: Apply "Dev build" before

=== Watch resources

....
$ cd ${entcore}
$ gulp adminV2-watch
....

This task will copy modified files from resources/ to springboard after code editing. Configure _springboardPath_ variable in _entcore/admin/gulpfile.admin.js_ to adjust your springboard path.

=== Webpack dev server

....
$ gulp adminV2-dev-server
....

This task will deploy files in memory after code editing, browser will refresh automatically.

Test app in browser => http://localhost:9000/admin

== Production build (before commit)

IMPORTANT: Before committing your work, it is mandatory to test app with production build

=== Build front

....
$ cd ${entcore}
$ gulp adminV2-build
....

NOTE: gulp adminV2-build will generate js files with hash code in filename

=== Build admin module  

....
$ gradle :admin:clean
$ gradle :admin:install
....

=== Deploy admin module to local springboard

....
$ cd ${springboard_dir}
$ rm -rf mods/org.entcore~admin~2.0-SNAPSHOT/
$ vertx runMod org.entcore~infra~2.0-SNAPSHOT -conf ent-core.embedded.json
....

Test app in browser => http://localhost:8090/admin

If OK then commit

IMPORTANT: After production build, to start again dev workflow, do an initial dev build (see "Dev build" chapter)
