= Development Environment Installation with Docker

This document describes the development environment installation for frontend and backend developers

1. Install Docker. Docler Compose
2. Install Git and configure SSH Key for Github
3. Clone a Springboard and run it 

NOTE: Code Editor software is up to developer's choice

== Basic Installation

=== 1. Install Docker. Docler Compose

1. Install Docker by following the reference documentation : https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
2. Grant non-root user to run Docker : https://docs.docker.com/install/linux/linux-postinstall/
3. Install Docker Compose by following the reference documentation : https://docs.docker.com/compose/install/#install-using-pip

WARNING: Step 2 is mandatory 

NOTE: Installation's documentation for others OS is available here : https://docs.docker.com/install/

=== 2. Install Git and configure SSH Key for Github

Install Git :

....
$ sudo apt install git
....

To set SSH key for Github, please follow the reference documentations below:

- https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
- https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

=== Clone a Springboard and run it

Get the Springboard's boilerplate repository :
....
    $ git clone git@github.com:entcore/springboard.git
    $ cd springboard
....

Run it
....
    ./build.sh clean init generateConf run
....

Availables command for build.sh sript are : 
....
                clean : clean springboard and docker's containers
                 init : fetch files and artefacts usefull for springboard's execution
         generateConf : generate an vertx configuration file (ent-core.json) from conf.properties
                  run : run databases and vertx in distinct containers
                 stop : stop containers
      integrationTest : run integration tests
           buildFront : fetch wigets and themes using Bower and run Gulp build. (/!\ first run can be long becouse of node-sass's rebuild).
      buildLocalFront : fetch wigets and themes using Bower and run Gulp build-local
              archive : make an archive with folder /mods /assets /static
              publish : upload the archive on nexus
....

== For Backend Development

=== Install JDK 8

Installation:

....
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer
....

Check installation:

....
$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
....

=== Install Gradle 4.5

Installation:

....
$ cd ~/apps
$ wget https://services.gradle.org/distributions/gradle-4.5-bin.zip
$ unzip gradle-4.5-bin.zip
$ ln -s gradle-4.5 gradle
$ rm gradle-4.5-bin.zip
....

Add binary to Path:

....
$ echo PATH=\"\$HOME/apps/gradle/bin:\$PATH\" >> ~/.profile
$ . ~/.profile
....

Check version:

....
$ gradle -v
....

=== Install your favortie Java IDE

=== Monitor the containers

Docker Compose names container with link:https://docs.docker.com/compose/reference/envvars/#compose_project_name[COMPOSE_PROJECT_NAME] convention.
In our context container's name are preprended with Springboard's directory name (${SPRINGBOARD_DIR}). 

You can run the below command to monitor your container's activity

* `docker ps` : List running's containers
* `docker ps -a` : List all containers
* `docker exec -it ${SPRINGBOARD_DIR}_neo4j_1 bin/neo4j-shell` : Open Neo4j's shell
* `docker exec -it ${SPRINGBOARD_DIR}_postgres_1 psql -U web-education ong` : Open PostgrSQL's shell
* `docker exec -it ${SPRINGBOARD_DIR}_mongo_1 mongo one_gridfs` : Open MongoDB's shell
* `docker exec -it ${SPRINGBOARD_DIR}_vertx_1 bash` : Open a Bash's shell on vertx's container
* `docker logs -f ${SPRINGBOARD_DIR}_vertx_1` : Display Vertx's logs

=== Chnage Vertx log level

=== Map local directories to container's volume

==== use your maven local
Uncoment
....
#    - ~/.m2:/home/vertx/.m2
....

==== Use your local data


=== Use Neo4j console

Add the next port's mapping in neo4j container's description 
....
    ports:
        - "7474:7474"
        - "7687:7687"
....

Enable Bolt Protocol in neo4j-conf/neo4j.conf
....
dbms.connector.bolt.enabled=true
....

Neo4j's Console is accessible via http://localhost:7474/browser

== For Frontend Development

=== Complete build

When you are cloning a new app, you should checkout to the `dev` branch and do a complete build. A complete build can also be done if there are any pulled changes.
Be sure that your `graddle.properties` versions in your springboard and your local app version are corresponding.

* Stop the springboard with `./build.sh stop`
* Build the app (see the sub-sections below)
* Remove the corresponding app folder in your springboard `mods` folder (you can remove all with `rm -rf mods/*`, but don't remove the folder `mods` itself)
* Run the springboard with `./build.sh run`

==== entcore

Inside entcore repo :

....
./build.sh clean install
....

==== infra-front

Inside infra-front repo :

....
./build.sh clean install
....

Inside entcore repo :

....
./build.sh clean infra install
....

==== specific apps

Inside your specific app repo :

....
./build.sh clean install
....

=== Watcher

When developping in the current app, you'll need to use a 'watcher' in order to apply your current changes for html/ts files. After launching the watcher command, you can save a file in order to copy the changes to the springboard.

WARNING: After watching an app, all your watched stuff in infra-front will be canceled. Re-watch in the infra-front to re-apply your changes.

NOTE: Watching .ts files can often lead to a watcher crash. Just re-run it if it happens.

==== entcore

....
./build.sh -s=springboardname -m=modulename watch
....
Default: -s=recette, -m=conversation

==== Other apps

....
./build.sh watch
....

=== Build front

If you are bulding front for the first time in the springboard, use :

....
./build.sh buildFront
....

For applying your local changes (for css, or any asset) :

* Be sure that your springboard `docker-compose.yml` contains the following node volumes :

....
    - ../theme-open-ent:/home/node/theme-open-ent
    - ../panda:/home/node/panda
    - ../entcore-css-lib:/home/node/entcore-css-lib
    - ../generic-icons:/home/node/generic-icons
....

* Be sure that these 4 repos (theme-open-ent, panda, entcore-css-lib and generic-icons) are cloned.
* For improving performance, go to the springboard `theme-conf.js` and comment one of the 'overriding' object (build themes one by one), this gains more than 5 minutes to finish.
* Use

....
./build.sh buildLocalFront
....

NOTE: If you are having an error with a file with a too long name, just run buildFront and buildLocalFront commands.

=== Apply 1D and 2D themes

You can have the two themes in two separate tabs of your browser. Go to the `conf.properties` and add a skin to `127.0.0.1`:

....
skins={"localhost:8090":"cg77", "127.0.0.1:8090":"cg771d"}
....

And re-run the springboard :

....
./build.sh stop generateConf run
....

Then, open one tab with `localhost:8090` for 1D and an other one with `127.0.0.1:8090` for 2D.