= Springboard Installation

== Get sources

NOTE: Add your SSH key to Github before by following instructions here https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Clone the repository:

....
    $ cd ~/ode/dev/projects
    $ git clone git@github.com:entcore/springboard.git
    $ cd springboard
....

== Build the Springboard

=== Get english translations

Open Digital Education is a french compagny. So application's label are french by default. 
All labels are available in english in a translations repository. 
Just clone it in `assets` directory of your Springboard.
....
   cd assets
   git clone git@github.com:web-education/translations.git i18n
   cd i18n
   git checkout <version>
....

=== Build backend

Go Back to your springboard's root and launch 
....
    cd ../..
    $ gradle clean init
....

In *conf.properties*, check and edit if needed the following properties:

....
    mode=dev

    host=http://localhost:8090
    httpProxy=true

    // Neo4J
    neo4jUri=http://localhost:7474

    // MongoDB
    dbName=one_gridfs
    mongoHost=localhost
    mongoPort=27017

    // PostgreSQL
    sqlUrl=jdbc:postgresql://localhost:5432/ong
    sqlUsername=web-education
    sqlPassword=We_1234

    // Configuration de l'apparence (1 skin doit être associé à une domaine)
    skins={"localhost:8090":"leo"}
....

Generate Vertx configuration (based on test.properties):

....
    $ gradle generateConf
....

=== Build frontend

....
    $ npm install
    $ gulp build
....

=== Start Springboard

NOTE: Neo4j, Postgre and mongodb must be running

Start Springboard:

....
    $ vertx runMod org.entcore~infra~<version> -conf ent-core.json
....

where <version> has to be replaced by entcore version number

=== Administration

1. Authenticate with user tom.mate/password at http://localhost:8090/
2. Go to http://localhost:8090/admin
3. Import users: go to _Annuaire > alimentation_ and click on _Importer_ button
4. Manage application rights: go to _Applications > roles applicatifs_ and create a _All_ right for needed application
5. Manage transverse rights: Sélection user avec droit tout
