=  Override Theme

The theme built process follow a waterfall composition :

1. Configure `parent` theme
2. Create a `child` theme that will inherit UI's artefacts from its `parent` ('img', 'js', 'fonts', 'template', 'css')
3. Customize UI's artefacts in `/overrides` directory under your child theme root


In `theme-conf.js` (under your springboard's root) configure the theme 'waterfall structure' 
with the `ovverriding` object  

[source]
----
overriding: [
    {
        parent: 'theme-open-ent',
        child: 'ode',
        skins: ['default', 'dyslexic']
    }
]
----

The whole theme 'waterfall structure' looks like above : 

[source]
----
/assets/themes
|── <your-parent-theme>
│   ├── css
│   ├── img
│   ├── js
│   ├── portal.html
│   ├── skins
│   └── template
└── <your-chil-theme>
    │   ├── overrides
    │   ├── img
    │   └── template
    │       ├── override.json
    ├── css
    ├── img
    ├── js
    ├── portal.html
    ├── skins
    └── template
----

So the theme built process (lauched with `./build.sh buildFront`) follow the next logic :

1. Fetch parent themes and its dependencies  
2. Copy overridable UI's artefacts ('img', 'js', 'fonts', 'template', 'css') from `parent theme` to `child theme`
3. Squash overridable UI's artefacts whith `child theme` overrides
4. Run build process (SASS ...)

== Template

[source]
----
<your-chil-theme>
    ├── overrides
        ├── img
        └── template
            ├── override.json
----

== CSS

`writing in progress`

== Image and Fonts

`writing in progress`