=  Override Theme

The theme's build process follows a waterfall composition :

1. Configure _parent theme_
2. Create a _child theme_ that will inherit UI's artefacts from its _parent_ ('img', 'js', 'fonts', 'template', 'css')
3. Customize UI's artefacts in `/overrides` directory under your _child theme_ root


In `theme-conf.js` (under your springboard's root) configure the theme 'waterfall structure' 
with the `ovverriding` object  

[source]
----
overriding: [
    {
        parent: 'theme-open-ent',
        child: 'ode',
        skins: ['default', 'dyslexic']
    }
]
----

The whole theme 'waterfall structure' looks like bellow : 

[source]
----
/assets/themes
|── <your-parent-theme>
│   ├── css
│   ├── img
│   ├── js
│   ├── portal.html
│   ├── skins
│   └── template
└── <your-child-theme>
    │   ├── overrides
    │   ├── img
    │   └── template
    │       ├── override.json
    ├── css
    ├── img
    ├── js
    ├── portal.html
    ├── skins
    └── template
----

So the theme built process (lauched with `./build.sh buildFront`) respects the next logic :

1. Fetch parent themes and its dependencies  
2. Copy overridable UI's artefacts ('img', 'js', 'fonts', 'template', 'css') from _parent theme_ to _child theme_
3. Squash overridable UI's artefacts whith _child theme_ specific overrides (placed under `<your-child-theme>/overrides/`)
4. Run build process (SASS ...)

== Template

Describe overriding policy into `<your-child-theme>/overrides/template/override.json` :

- *key* must be a template's directroy (so an application name)
- *value* muste be an string array containing template's name   

[source]
----

{
  "auth": ["activation-form", "forgot-form"],
  "portal": ["conversation-unread"]
}
----

Create driectories and templates you declare into `override.json` under `<your-child-theme>/overrides/template/``

[source]
----
<your-child-theme>
    ├── overrides
        ├── img
        └── template
            ├── override.json
----

WARNING: If you want to keep _parent theme_ specific templates you need to  
`cp <your-parent-theme>/template/ <your-child-theme>/overrides/template/` and follow above instructions 

== CSS

`writing in progress`

== Image and Fonts

`writing in progress`